const PAC_CONFIG = {
    DEFAULT_UPDATE_FREQUENCY: 3600000,
    DEFAULT_BEACON_SUBMIT_IN_BATCH: 100,
    DEFAULT_DB_BACKUP_FREQUENCY: 86400,
    INCIDENT_REPORT_COLLECTION: 'incident_reports',
    MERKLE_TREE_COLLECTION: 'merkle_tree',
    IPFS_HISTORY_COLLECTION: 'ipfs_history',
}

module.exports = PAC_CONFIG;
